Repository jhudsl/AnVIL_Book_Instructor_Guide, pull requests merged in 2021-11, with the labels that each got.

#11 Subdivide chapters in subsections
  03_Account_setup.Rmd
  05_Class_setup.Rmd
  07_Class_checklist.Rmd
  07_Student_account_setup.Rmd
  A_Student_account_setup.Rmd
  About.Rmd
  _bookdown.yml
  index.Rmd
Labels: documentation

#24 🔄 Synced file(s) with jhudsl/DaSL_Course_Template_Bookdown
  .github/ISSUE_TEMPLATE/course-content-add.md
  .github/ISSUE_TEMPLATE/course-problem-report.md
  .github/workflows/render-bookdown.yml
  code_of_conduct.md
  scripts/render-all.R
Labels: sync

#28 🔄 Synced file(s) with jhudsl/DaSL_Course_Template_Bookdown
  .github/workflows/render-preview.yml
Labels: sync

#35 🔄 Synced file(s) with jhudsl/DaSL_Course_Template_Bookdown
  .github/workflows/render-preview.yml
Labels: sync

#69 Class setup
  03_Account_setup.Rmd
  05_Class_setup.Rmd
  resources/dictionary.txt
Labels: documentation, Google Doc transfer
